### PR TITLE
artik5: support wifi (preliminary devicetree)

### PR DESCRIPTION
**Pull request by mlyle**
(pending inclusion in upstream)

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Thanks, I'll test out tomorrow!

**Comment by mlyle** [comment]
Note that you need one thing-- set rootdev 2     / saveenv on the boot.  Have an environment file in my image generator.

**Comment by RobertCNelson** [comment]
Yeah i saw that message on lkml, based on:

```
&mshc_2 {
```

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm/boot/dts/exynos3250-artik5-eval.dts?h=v4.15#n24

it 'should' have been always /dev/mmcblk2 since v4.4.3/v4.5.x as that's when the mmc parallel probing and thus lock mmc name to dt node name came about.

Prior to that the mmc # was always a race condition, usually probed in order.

Regards,

**Comment by mlyle** [comment]
> it 'should' have been always /dev/mmcblk2 since v4.4.3/v4.5.x as that's when the mmc parallel probing and thus lock mmc name to dt node name came about.

I don't think that's true for dwmmc --- I followed the code about to see if I could do good things with aliases to pin it the same, and it looks like no one uses the unit number at the end of the alias in dwmmc or dwmmc_exynos.  Instead it's the order in the dt file that counts.

I'm considering plumbing it through, but it's a pain.

**Comment by RobertCNelson** [comment]
So here's the patches, that changed it.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/mmc/core?id=520bd7a8b4152aacfbd34eb7f7a447354b631039

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/mmc?id=9aaf3437aa72ed5370bf32c99580a3fa2c330e3d

We might want to use the alias option to fix it on mainline.

Regards,

**Comment by mlyle** [comment]
It's possible I did something wrong, but that didn't work for me, and it doesn't look plumbed.

The only thing that dwmmc does with the devicetree unit id is:

```
	if (host->dev->of_node) {
		ctrl_id = of_alias_get_id(host->dev->of_node, "mshc");
		if (ctrl_id < 0)
			ctrl_id = 0;
	} else {
		ctrl_id = to_platform_device(host->dev)->id;
	}
	if (drv_data && drv_data->caps)
		mmc->caps |= drv_data->caps[ctrl_id];
```

And never touches ctrl_id or of_alias_get_id again.  And stuff gets probed/detected in the order it's in the dtb.

**Pull request merged**
